# Stage 1: Build React app
FROM node:20.11-alpine
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm i
COPY frontend ./
# RUN npm run build

CMD ["npm", "start"]

# Stage 2: Create Nginx server
# FROM nginx:1.19.0
# COPY --from=builder /app/build /usr/share/nginx/html
# EXPOSE 80
# ENTRYPOINT ["nginx", "-g", "daemon off;"]
